exports.RECLAIM_PROVIDER_ID = {
  twitter: 'TWITTER_ANALYTICS_VIEWS',
  github: 'GITHUB_ACCOUNT_VERIFICATION',
  medium: 'MEDIUM_PUBLICATIONS_VERIFICATION',
};

exports.RECLAIM_APP_ID = {
  TWITTER_ANALYTICS_VIEWS: 'your-twitter-app-id',
  GITHUB_ACCOUNT_VERIFICATION: 'your-github-app-id',
  MEDIUM_PUBLICATIONS_VERIFICATION: 'your-medium-app-id',
};